/* TEAM EYSL v173 — canonical attendance + roster + mypage cleanup */
(()=>{if(window.__EYSL_CANONICAL_V173__)return;window.__EYSL_CANONICAL_V173__=true;
const SEP19='a606d356-fb6b-424b-b4f8-b7226233ed6b';const ROSTER=['민선/97/여/강남','재연/91/여/강남','승현/99/남/양재','창두/93/남/구로','아람/87/여/관악','승희/94/여/송파','준석/94/남/영등포','재건/90/남/강동','윤/99/여/중랑','종명/89/남/강남','유빈/97/여/성북','태진/85/남/용산','혜린/97/여/성북','광섭/91/남/송파','서희/82/여/양재','준혁/94/남/강남','규리/01/여/경기','민석/00/남/잠실','나연/96/여/강남','민정/86/여/서초'];
function forceRoster(){const t=window.trainings?.[SEP19];if(t){t.participants=[...ROSTER];t.capacity=20}}
async function attendance(){if(!currentUser?.memberId)return[];const {data,error}=await dbClient.rpc('get_unified_member_attendance_v1',{p_member_id:currentUser.memberId});if(error){console.error(error);return[]}return(data||[]).map(x=>({date:x.activity_date,title:x.title||'팀아이슬 훈련',status:x.status}))}
function removeSummary(){const p=document.getElementById('mypage');if(!p)return;const a=[...p.querySelectorAll('*')].find(x=>!x.children.length&&x.textContent.trim()==='ACTIVITY');if(a){let c=a;while(c&&c!==p&&!/훈련 참여|PB 갱신/.test(c.textContent||''))c=c.parentElement;if(c&&c!==p)c.remove()}const h=[...p.querySelectorAll('h1,h2,h3')].find(x=>x.textContent.trim()==='내 활동 요약');if(h)h.remove()}
const oldLoad=window.loadPersistentContent;if(typeof oldLoad==='function')window.loadPersistentContent=async function(){const r=await oldLoad.apply(this,arguments);forceRoster();return r};
const oldTrain=window.renderTrainingList;if(typeof oldTrain==='function')window.renderTrainingList=function(){forceRoster();return oldTrain.apply(this,arguments)};
const oldOpen=window.openTraining;if(typeof oldOpen==='function')window.openTraining=function(){forceRoster();return oldOpen.apply(this,arguments)};
const oldStatus=window.renderApplyStatus;if(typeof oldStatus==='function')window.renderApplyStatus=async function(){if(selectedTrainingId!==SEP19)return oldStatus.apply(this,arguments);forceRoster();const box=document.getElementById('applyStatusBody'),t=trainings[SEP19];let live=[];try{live=await fetchApplicationPeople(SEP19)}catch(_){}const by=new Map(live.filter(x=>x.type==='participant'&&x.name&&x.name!=='회원').map(x=>[x.name,x]));const people=ROSTER.map(name=>{const p=by.get(name)||{name,type:'participant'};return `<div class="applyPerson">${applicationAvatar(p)}<div class="grow"><b>${escHtml(name)}</b><p class="meta">신청완료</p></div></div>`}).join('');box.innerHTML=`<div class="detail"><div class="detailrow"><b>훈련</b><span>${escHtml(t.title)}</span></div><div class="detailrow"><b>신청</b><span>20/20</span></div><div class="detailrow"><b>대기</b><span>${t.waitlist?.length||0}명</span></div></div><div class="section"><h2>신청완료 20명</h2></div><div class="card">${people}</div>`};
const oldAtt=window.renderAttendance;if(typeof oldAtt==='function')window.renderAttendance=async function(){window.attendanceHistory=await attendance();return oldAtt.apply(this,arguments)};
const oldMy=window.renderMyPage;if(typeof oldMy==='function')window.renderMyPage=function(){const r=oldMy.apply(this,arguments);requestAnimationFrame(removeSummary);return r};
function init(){forceRoster();removeSummary()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();