/* TEAM EYSL race UI v145 */
(()=>{
 if(window.__RACE_UI_V145__)return;window.__RACE_UI_V145__=true;
 const esc=s=>window.escHtml?escHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uniq=a=>[...new Set((a||[]).map(x=>String(x||'').trim()).filter(Boolean))];
 const selectedRace=()=>window.race||null;
 function fixForm(){const g=document.getElementById('raceGroup');if(g){let i=g;if(g.tagName!=='INPUT'){i=document.createElement('input');i.id='raceGroup';i.type='text';g.replaceWith(i)}i.placeholder='예) 2그룹';i.value=window.raceApplication?.group||'';i.style.color='#111'}['raceS1','raceS2'].forEach(id=>{const el=document.getElementById(id);if(!el)return;if(!el.querySelector('option[value=""]'))el.insertAdjacentHTML('afterbegin','<option value="">선택해주세요</option>');if(!window.raceApplication)el.value='' });const box=document.getElementById('relayChoices');if(box){const opts=uniq(selectedRace()?.relays),sel=uniq(window.raceApplication?.relays);box.innerHTML=opts.map(x=>`<button type="button" class="bigChoice ${sel.includes(x)?'on':''}" onclick="toggleRelay(this)">${esc(x)}</button>`).join('')}const no=document.getElementById('noRelay');if(no)no.classList.toggle('on',!!window.raceApplication?.noRelay)}
 const oldOpen=window.openRaceApply;window.openRaceApply=function(){const out=typeof oldOpen==='function'?oldOpen.apply(this,arguments):undefined;fixForm();requestAnimationFrame(fixForm);return out};
 function detailLine(d){const personal=[d?.s1,d?.s2].filter(Boolean).join(' · ')||'개인종목 미입력';const relay=d?.noRelay?'단체전 참가 안 함':uniq(d?.relays).join(' · ')||'단체전 미선택';return `${esc(personal)}<br>${esc(relay)}`}
 async function manualRoster(id){try{const {data,error}=await dbClient.from('activities').select('details').eq('id',id).single();if(error)throw error;return Array.isArray(data?.details?.manual_race_roster)?data.details.manual_race_roster:[]}catch(e){console.error(e);return []}}
 const oldStatus=window.openGenericApplyStatus;window.openGenericApplyStatus=async function(kind,id){if(kind!=='race')return oldStatus.apply(this,arguments);applyStatusBackPage='raceList';showPage('applyStatus');const box=document.getElementById('applyStatusBody');box.innerHTML='<div class="card meta">신청현황 불러오는 중...</div>';const item=races.find(x=>x.id===id)||selectedRace();if(!item)return;try{const live=(await fetchApplicationPeople(id)).filter(x=>x.type==='participant'),manual=await manualRoster(id),seen=new Set(),people=[];for(const p of live){const d=p.details||{};people.push({name:p.name,avatar:p,details:d});seen.add(p.name);if(d.applicantName)seen.add(d.applicantName)}for(const d of manual){const key=d.nickname||d.name;if(seen.has(key)||seen.has(d.name))continue;people.push({name:key,details:d});seen.add(key);if(d.name)seen.add(d.name)}for(const name of (item.historicalParticipants||[])){if(seen.has(name))continue;people.push({name,details:{}});seen.add(name)}for(const name of (item.participants||[])){if(seen.has(name))continue;people.push({name,details:{}});seen.add(name)}const rows=people.map(p=>`<div class="applyPerson">${p.avatar?applicationAvatar(p.avatar):`<div class="applyAvatar fallback">${esc(String(p.name||'?').slice(0,1))}</div>`}<div class="grow"><b>${esc(p.name)}</b><p class="meta">신청완료<br>${detailLine(p.details)}</p></div></div>`).join('')||'<div class="meta">신청자가 없습니다.</div>';box.innerHTML=`<div class="detail"><div class="detailrow"><b>대회</b><span>${esc(item.title)}</span></div><div class="detailrow"><b>신청</b><span>${people.length}명</span></div></div><div class="section"><h2>신청완료 ${people.length}명</h2></div><div class="card">${rows}</div>`}catch(e){console.error(e);box.innerHTML='<div class="card meta">신청현황을 불러오지 못했습니다.</div>'}};
})();