/* TEAM EYSL race UI v142 */
(()=>{
 if(window.__RACE_UI_V142__)return;window.__RACE_UI_V142__=true;
 const esc=s=>window.escHtml?escHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uniq=a=>[...new Set((a||[]).map(x=>String(x||'').trim()).filter(Boolean))];
 function selectedRace(){return window.race||null}
 function groupPlaceholder(){const el=document.getElementById('raceGroup');if(!el)return;let input=el;if(el.tagName!=='INPUT'){input=document.createElement('input');input.id='raceGroup';input.type='text';el.replaceWith(input)}input.placeholder='예) 2그룹';input.style.color='#111';input.value=window.raceApplication?.group||'';}
 function emptyPersonalSelect(id){const el=document.getElementById(id);if(!el)return;const values=['','자유형 50m','배영 50m','평영 50m','접영 50m','개인혼영 100m'];const cur=window.raceApplication?.[id==='raceS1'?'s1':'s2']||'';el.innerHTML=values.map(v=>`<option value="${esc(v)}">${v?esc(v):''}</option>`).join('');el.value=cur;}
 function relayOptions(){const r=selectedRace();return uniq(r?.relays||[])}
 function renderRelays(){const box=document.getElementById('relayChoices');if(!box)return;const selected=uniq(window.raceApplication?.relays);const opts=relayOptions();box.innerHTML=opts.map(x=>`<button type="button" class="bigChoice ${selected.includes(x)?'on':''}" onclick="toggleRelay(this)">${esc(x)}</button>`).join('');const no=document.getElementById('noRelay');if(no)no.classList.toggle('on',!!window.raceApplication?.noRelay);}
 function fixForm(){groupPlaceholder();emptyPersonalSelect('raceS1');emptyPersonalSelect('raceS2');renderRelays();}
 const oldOpen=window.openRaceApply;window.openRaceApply=function(){if(typeof oldOpen==='function')oldOpen.apply(this,arguments);fixForm();requestAnimationFrame(fixForm)};
 function detailLine(d){const personal=[d?.s1,d?.s2].filter(Boolean).join(' · ')||'개인종목 미입력';const relay=d?.noRelay?'단체전 참가 안 함':uniq(d?.relays).join(' · ')||'단체전 미선택';return `${personal}<br>${relay}`}
 async function manualRoster(id){try{const {data,error}=await dbClient.from('activities').select('details').eq('id',id).single();if(error)throw error;return Array.isArray(data?.details?.manual_race_roster)?data.details.manual_race_roster:[]}catch(e){console.error(e);return []}}
 const oldStatus=window.openGenericApplyStatus;window.openGenericApplyStatus=async function(kind,id){if(kind!=='race')return oldStatus.apply(this,arguments);applyStatusBackPage='raceList';showPage('applyStatus');const box=document.getElementById('applyStatusBody');box.innerHTML='<div class="card meta">신청현황 불러오는 중...</div>';const item=(races.find(x=>x.id===id)||selectedRace());if(!item)return box.innerHTML='<div class="card meta">대회 정보를 찾을 수 없습니다.</div>';try{const live=(await fetchApplicationPeople(id)).filter(x=>x.type==='participant');const manual=await manualRoster(id);const seen=new Set();const people=[];for(const p of live){const d=p.details||{};people.push({name:p.name,avatar:p,details:d});seen.add(d.applicantName||p.name)}for(const d of manual){if(seen.has(d.name)||seen.has(d.nickname))continue;people.push({name:d.nickname||d.name,details:{applicantName:d.name,birthDate:d.birthDate,phone:d.phone,group:d.group,s1:d.s1,s2:d.s2,relays:d.relays||[],noRelay:d.noRelay}})}const rows=people.map(p=>`<div class="applyPerson">${p.avatar?applicationAvatar(p.avatar):`<div class="applyAvatar fallback">${esc(String(p.name||'?').slice(0,1))}</div>`}<div class="grow"><b>${esc(p.name)}</b><p class="meta">신청완료<br>${detailLine(p.details)}</p></div></div>`).join('')||'<div class="meta">신청자가 없습니다.</div>';box.innerHTML=`<div class="detail"><div class="detailrow"><b>대회</b><span>${esc(item.title)}</span></div><div class="detailrow"><b>신청</b><span>${people.length}명</span></div></div><div class="section"><h2>신청완료 ${people.length}명</h2></div><div class="card">${rows}</div>`}catch(e){console.error(e);box.innerHTML='<div class="card meta">신청현황을 불러오지 못했습니다.</div>'}};
})();
