const VERSION='team-eysl-final140-lean-runtime';
const CACHE=`team-eysl-${VERSION}`;
const PRECACHE=['/manifest.webmanifest','/icon-192.png','/icon-512.png','/apple-touch-icon.png','/timestamp-v94.js','/join-date-v96.js','/activity-comments-v98.js','/application-order-v99.js','/manual-roster-v100.js','/ui-order-v112.js','/remove-aggregation-v113.js','/notice-poll-v115.js','/notice-upload-fix-v116.js','/notice-engagement-v117.js','/notice-interaction-fix-v118.js','/notice-deadline-layout-v121.js','/race-attachment-v123.js','/race-time-fields-v124.js','/race-application-v125.js','/auth-session-v126.js'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(PRECACHE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())});
async function navigationResponse(req){try{const res=await fetch(req,{cache:'no-store'});if(!res.ok)return res;let html=await res.text();const scripts=[['timestamp-v94.js','final140'],['join-date-v96.js','final140'],['activity-comments-v98.js','final140'],['application-order-v99.js','final140'],['manual-roster-v100.js','final140'],['ui-order-v112.js','final140'],['remove-aggregation-v113.js','final140'],['notice-poll-v115.js','final140'],['notice-upload-fix-v116.js','final140'],['notice-engagement-v117.js','final140'],['notice-interaction-fix-v118.js','final140'],['notice-deadline-layout-v121.js','final140'],['race-attachment-v123.js','final140'],['race-time-fields-v124.js','final140'],['race-application-v125.js','final140'],['auth-session-v126.js','final140']];for(const [file,v] of scripts){if(!html.includes('/'+file))html=html.replace('</body>',`<script src="/${file}?v=${v}"></script></body>`)}return new Response(html,{status:res.status,statusText:res.statusText,headers:new Headers(res.headers)})}catch(_){return new Response('TEAM EYSL offline',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(req.mode==='navigate'){event.respondWith(navigationResponse(req));return}event.respondWith(fetch(req,{cache:'no-store'}).catch(()=>caches.match(req)))});
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{}}catch(_){try{data={body:event.data?event.data.text():''}}catch(__){data={}}}const title=data.title||'TEAM EYSL';event.waitUntil(self.registration.showNotification(title,{body:data.body||'새 알림이 도착했어요.',icon:data.icon||'/icon-192.png',badge:data.badge||'/icon-192.png',tag:data.tag||'team-eysl',data:{url:data.url||'/'}}))});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification?.data?.url||'/';event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if('focus'in client){client.navigate(target).catch(()=>{});return client.focus()}}if(clients.openWindow)return clients.openWindow(target)}))});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});